### ISSUE TITLE
Unit 3 - The 7 Habits for Running Highly Effective Lean Startup Experiments by Ash Maurya Link dead

### ISSUE THREAD

**Issue by rompic** [jezhumble/lapm-public-lectures#1]
Hi thanks for all this material.
I noticed that the link to The 7 Habits for Running Highly Effective Lean Startup Experiments by Ash Maurya in Unit 3 is dead (404)
I only found a copy on archive.org:
https://web.archive.org/web/20180918093952/https://blog.leanstack.com/the-7-habits-for-running-highly-effective-lean-startup-experiments-f1daaa93f85b

**Comment by isikkara** [comment]
It is currently working. The link is: https://blog.leanstack.com/the-7-habits-for-running-highly-effective-lean-startup/

**Comment by rompic** [comment]
then i guess we can close this one
